from normal.normalSudoku import NormalSudoku

def createSudoku():
    return createSudoku3()
    
def createSudoku1():
    sudoku = NormalSudoku(9)
    sudoku.Set( 0, 0, 9, True)
    sudoku.Set( 0, 8, 6, True)
    sudoku.Set( 1, 3, 9, True)
    sudoku.Set( 1, 6, 5, True)    
    sudoku.Set( 1, 7, 2, True)
    sudoku.Set( 2, 0, 5, True)
    sudoku.Set( 2, 2, 7, True)
    sudoku.Set( 2, 4, 3, True)
    sudoku.Set( 2, 5, 6, True)
    sudoku.Set( 2, 7, 1, True)
    sudoku.Set( 3, 0, 2, True)
    sudoku.Set( 3, 2, 4, True)
    sudoku.Set( 4, 3, 6, True)
    sudoku.Set( 4, 5, 2, True)
    sudoku.Set( 5, 6, 7, True)
    sudoku.Set( 5, 8, 2, True)
    sudoku.Set( 6, 1, 2, True)
    sudoku.Set( 6, 3, 1, True)
    sudoku.Set( 6, 4, 7, True)
    sudoku.Set( 6, 6, 6, True)
    sudoku.Set( 6, 8, 4, True)
    sudoku.Set( 7, 1, 9, True)
    sudoku.Set( 7, 2, 1, True)
    sudoku.Set( 7, 5, 5, True)
    sudoku.Set( 8, 0, 3, True)
    sudoku.Set( 8, 8, 7, True)
    sudoku.DoChange() # set the changes
    return sudoku

def createSudoku2():
    sudoku= NormalSudoku(9)
    sudoku.Set( 0, 0, 4)
    sudoku.Set( 0, 6, 9)
    sudoku.Set( 0, 7, 3)
    sudoku.Set( 0, 8, 8)
    sudoku.Set( 1, 1, 3)
    sudoku.Set( 1, 2, 2)
    sudoku.Set( 1, 4, 9)
    sudoku.Set( 1, 5, 4)
    sudoku.Set( 1, 6, 1)
    sudoku.Set( 2, 1, 9)
    sudoku.Set( 2, 2, 5)
    sudoku.Set( 2, 3, 3)
    sudoku.Set( 2, 6, 2)
    sudoku.Set( 2, 7, 4)
    sudoku.Set( 3, 0, 3)
    sudoku.Set( 3, 1, 7)
    sudoku.Set( 3, 3, 6)
    sudoku.Set( 3, 5, 9)
    sudoku.Set( 3, 8, 4)
    sudoku.Set( 4, 0, 5)
    sudoku.Set( 4, 1, 2)
    sudoku.Set( 4, 2, 9)
    sudoku.Set( 4, 5, 1)
    sudoku.Set( 4, 6, 6)
    sudoku.Set( 4, 7, 7)
    sudoku.Set( 4, 8, 3)
    sudoku.Set( 5, 0, 6)
    sudoku.Set( 5, 2, 4)
    sudoku.Set( 5, 3, 7)
    sudoku.Set( 5, 5, 3)
    sudoku.Set( 5, 7, 9)
    sudoku.Set( 6, 0, 9)
    sudoku.Set( 6, 1, 5)
    sudoku.Set( 6, 2, 7)
    sudoku.Set( 6, 5, 8)
    sudoku.Set( 6, 6, 3)
    sudoku.Set( 7, 2, 3)
    sudoku.Set( 7, 3, 9)
    sudoku.Set( 7, 6, 4)
    sudoku.Set( 8, 0, 2)
    sudoku.Set( 8, 1, 4)
    sudoku.Set( 8, 4, 3)
    sudoku.Set( 8, 6, 7)
    sudoku.Set( 8, 8, 9)
    sudoku.DoChange()
    return sudoku

def createSudoku3():
    sudoku= NormalSudoku(9)
    sudoku.Set( 0, 1, 8,True)
    sudoku.Set( 0, 4, 9,True)
    sudoku.Set( 0, 7, 3,True)
    sudoku.Set( 1, 1, 3,True)
    sudoku.Set( 1, 7, 6,True)
    sudoku.Set( 1, 8, 9,True)
    sudoku.Set( 2, 0, 9,True)
    sudoku.Set( 2, 2, 2,True)
    sudoku.Set( 2, 4, 6,True)
    sudoku.Set( 2, 5, 3,True)
    sudoku.Set( 2, 6, 1,True)
    sudoku.Set( 2, 7, 5,True)
    sudoku.Set( 2, 8, 8,True)
    sudoku.Set( 3, 1, 2,True)
    sudoku.Set( 3, 3, 8,True)
    sudoku.Set( 3, 5, 4,True)
    sudoku.Set( 3, 6, 5,True)
    sudoku.Set( 3, 7, 9,True)
    sudoku.Set( 4, 0, 8,True)
    sudoku.Set( 4, 1, 5,True)
    sudoku.Set( 4, 2, 1,True)
    sudoku.Set( 4, 3, 9,True)
    sudoku.Set( 4, 5, 7,True)
    sudoku.Set( 4, 7, 4,True)
    sudoku.Set( 4, 8, 6,True)
    sudoku.Set( 5, 0, 3,True)
    sudoku.Set( 5, 1, 9,True)
    sudoku.Set( 5, 2, 4,True)
    sudoku.Set( 5, 3, 6,True)
    sudoku.Set( 5, 5, 5,True)
    sudoku.Set( 5, 6, 8,True)
    sudoku.Set( 5, 7, 7,True)
    sudoku.Set( 6, 0, 5,True)
    sudoku.Set( 6, 1, 6,True)
    sudoku.Set( 6, 2, 3,True)
    sudoku.Set( 6, 4, 4,True)
    sudoku.Set( 6, 6, 9,True)
    sudoku.Set( 6, 7, 8,True)
    sudoku.Set( 6, 8, 7,True)
    sudoku.Set( 7, 0, 2,True)
    sudoku.Set( 7, 7, 1,True)
    sudoku.Set( 7, 8, 5,True)
    sudoku.Set( 8, 1, 1,True)
    sudoku.Set( 8, 4, 5,True)
    sudoku.Set( 8, 7, 2,True)
    sudoku.DoChange()
    return sudoku
